services:
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
      target: prod
    ports:
      - "8080:8080"
    env_file:
      - .env

networks:
  default:
    name: app-network
