app = 'nextjs-nestjs-react-native-expo-turbo'
primary_region = 'sin'

[build]
  dockerfile = "server/api-gateway/Dockerfile"

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
