packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.51.9
  eslint: ^9.7.0
  prettier: ^3.3.3
  typescript: ^5.5.3
  zod: ^3.23.8
  jest: ^29.5.0
  "@types/node": ^20.3.1
  "@types/jest": ^29.5.2
  dotenv-cli: ^7.4.2
  tailwindcss: ^3.4.10
  ramda: ^0.30.1
  "@types/ramda": ^0.30.1
  uuid: ^10.0.0
  "@types/uuid": ^10.0.0
  date-fns: ^3.6.0

catalogs:
  nestjs:
    eslint: ^8.42.0
    "@nestjs/cache-manager": ^2.2.2
    cache-manager: ^5.2.3
    cache-manager-redis-store: ^3.0.1
    redis: ^4.6.10
    "@nestjs/common": ^10.0.0
    "@nestjs/core": ^10.0.0
    "@nestjs/cli": ^10.0.0
    "@nestjs/microservices": ^10.0.0
    "@nestjs/schematics": ^10.0.0
    "@nestjs/testing": ^10.0.0
    "@nestjs/platform-fastify": ^10.0.0
    "@nestjs/axios": ^3.0.2
    "@nestjs/swagger": ^7.4.0
    "@nestjs/config": ^3.2.3
    "@fastify/multipart": ^8.3.0
    "@fastify/static": 7.0.4
    class-transformer: ^0.5.1
    class-validator: ^0.14.1
    reflect-metadata: ^0.2.0
    rxjs: ^7.8.1
    source-map-support: ^0.5.21
    supertest: ^7.0.0
    ts-jest: ^29.1.0
    ts-loader: ^9.4.3
    ts-node: ^10.9.1
    tsconfig-paths: ^4.2.0
    "@types/supertest": ^6.0.0
    nats: ^2.28.1
    drizzle-kit: ^0.24.0
    drizzle-orm: ^0.33.0
    postgres: ^3.4.4
    eslint-plugin-drizzle: ^0.2.3
    pg: ^8.12.0
    drizzle-zod: ^0.5.1
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0

